### ISSUE TITLE
store.py example doesn't work with version 1.5.0

### ISSUE THREAD

**Issue by clause** [drafter-edu/drafter#18]
The store.py example from the Drafter workbook (https://drafter-edu.github.io/drafter/_downloads/b810a7b8039f6ee3810e2d12adff25aa/store.py) doesn't work with version 1.5.0. Running the application is fine but clicking on a purchse button results in the following:

`
500 Internal Server Error
Sorry, the requested URL http://localhost:8080/purchase?--submit-button=Sword caused an error.

You might want to return to the [index](http://localhost:8080/) page.

Original error message:

Error creating page.
Error in purchase:
purchase() missing 1 required positional argument: 'name'

Traceback (most recent call last):
  File "/Users/clause/Library/Python/3.10/lib/python/site-packages/drafter/server.py", line 264, in bottle_page
    page = original_function(*args, **kwargs)
TypeError: purchase() missing 1 required positional argument: 'name'

None
Available routes:

'index':
'index':
'purchase':
`
